FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
COPY /home/akshayn/DevelopersDen/akshaynambly_info_chain.crt /etc/ssl/certs/akshaynambly_info_chain.crt
COPY /home/akshayn/DevelopersDen/akshaynambly_info.key /etc/ssl/private/akshaynambly_info.key